### ISSUE TITLE
As an unregistered user, I want to be able to register as a user in order to participate in games and compete with other users.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#1]
- [x] Upon successful registration, the user is automatically logged in and the logged in landing page is shown.
- [x] The now logged in user can log out and log in again.
- [x] If the registration is not successful, an error message is shown (e.g. ``The selected username has already been chosen by another user.''), and the user is taken back to the registration page.

- [x] sopra-fs24-group-37/sopra-fs24-client#1
- [x] sopra-fs24-group-37/sopra-fs24-client#2
- [x] sopra-fs24-group-37/sopra-fs24-client#3
- [x] sopra-fs24-group-37/sopra-fs24-server#21
- [x] sopra-fs24-group-37/sopra-fs24-client#4
- [x] sopra-fs24-group-37/sopra-fs24-server#23
- [x] sopra-fs24-group-37/sopra-fs24-server#24
