### ISSUE TITLE
As a player, I must be able to view the picture describing the location that has to be guessed. The map which allows me to localize this picture should be displayed once the game has started as well.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#10]
- [ ] After clicking the "Start game" button, the website redirects to the game interface and a countdown is displayed together with the text "Get ready for the first question!".
- [ ] Once the countdown is over, the first picture is displayed together with a map of Switzerland.
- [ ] The timer will start automatically once the picture is shown, and the timer value is consistent amongst all the players.

- [x] sopra-fs24-group-37/sopra-fs24-client#27
- [x] sopra-fs24-group-37/sopra-fs24-client#28
- [x] sopra-fs24-group-37/sopra-fs24-client#29
- [x] sopra-fs24-group-37/sopra-fs24-client#30
- [x] sopra-fs24-group-37/sopra-fs24-client#31
- [x] sopra-fs24-group-37/sopra-fs24-client#32
- [x] sopra-fs24-group-37/sopra-fs24-server#67
- [x] sopra-fs24-group-37/sopra-fs24-server#94
- [x] sopra-fs24-group-37/sopra-fs24-server#110
- [x] sopra-fs24-group-37/sopra-fs24-server#140
- [x] sopra-fs24-group-37/sopra-fs24-server#139
