### ISSUE TITLE
As a player, I must be able to localize the picture on the map.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#11]
- [ ] Players can localize the picture by clicking on the map before the countdown ends.
- [ ] Players can change the selected location by clicking on the map again before the countdown ends. 
- [ ] Once the timer is over, the players cannot adjust the location anymore.
- [ ] If a player does not locate the picture by clicking on the map, a null answer will be submitted.
- [x] sopra-fs24-group-37/sopra-fs24-client#33
- [x] sopra-fs24-group-37/sopra-fs24-client#34
- [x] sopra-fs24-group-37/sopra-fs24-client#35
- [x] sopra-fs24-group-37/sopra-fs24-client#36
- [x] sopra-fs24-group-37/sopra-fs24-server#72
