### ISSUE TITLE
As a player, I want to be able to see the locations chosen on the map by other players.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#12]
- [ ] When a player has selected a location on the map, the map will have an icon representative of the player displayed throughout the entire timer period.
- [ ] If the player decides to change his selection, the map will be updated with his new selection.
- [ ] His selection will remain unknown to other users until the round timer ends.
- [ ] After the timer has ended, the other players' selections appear on the same map.
- [x] sopra-fs24-group-37/sopra-fs24-client#41
- [x] sopra-fs24-group-37/sopra-fs24-client#42
- [x] sopra-fs24-group-37/sopra-fs24-server#82
- [x] sopra-fs24-group-37/sopra-fs24-server#111
