### ISSUE TITLE
As a player, I want to see after each completed round the final selection of the other players and which player won the round making the most accurate guess.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#13]
- [ ] The maps API must return the actual location of the image shown and be verified whether the player's answer corresponds to the location.
- [ ] If the player's guess is close enough to the actual location stored by the map API, he/she will score 1 point. Otherwise, no points are scored.
- [ ] When the timer ends, the players will be notified if they got the question right or not. This page will be displayed for a set time before automatically redirecting to the next question.
- [x] sopra-fs24-group-37/sopra-fs24-server#73
- [x] sopra-fs24-group-37/sopra-fs24-client#37
- [x] sopra-fs24-group-37/sopra-fs24-client#38
- [x] sopra-fs24-group-37/sopra-fs24-server#76
- [x] sopra-fs24-group-37/sopra-fs24-server#111
- [x] sopra-fs24-group-37/sopra-fs24-server#112
