### ISSUE TITLE
As a player, I want to be able to use each of the 3 Game power ups once in a game session to enhance my gaming experience.

### ISSUE THREAD

**Issue by DiaHidvegi** [sopra-fs24-group-37/sopra-fs24-server#135]
- [ ] As a player I want to be able to use Powerups such as: double score; canton hint; triple hint
- [ ] As a player I want to be able to see how many powerups i still have of each type

- [x] sopra-fs24-group-37/sopra-fs24-server#119
- [x] sopra-fs24-group-37/sopra-fs24-server#120
- [x] sopra-fs24-group-37/sopra-fs24-server#122
- [x] sopra-fs24-group-37/sopra-fs24-server#121
- [x] sopra-fs24-group-37/sopra-fs24-server#133
- [x] sopra-fs24-group-37/sopra-fs24-client#74
- [x] sopra-fs24-group-37/sopra-fs24-client#75
- [x] sopra-fs24-group-37/sopra-fs24-client#76
