### ISSUE TITLE
As a player, I want to be able to see who scored in the current round, as well as the total score of all the players on the leaderboard.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#14]
- [ ] After a set amount of questions had been answered, the session is terminated with a page saying "Game has Ended. Compiling scores..."
- [ ] Individual scores for each question were recorded as the game progresses, and added up when the round ends.
- [ ] Scores are correctly added for each player.
- [ ] The leaderboard will rank all players according to their final cumulative score in descending order.
- [x] sopra-fs24-group-37/sopra-fs24-client#39
- [x] sopra-fs24-group-37/sopra-fs24-client#40
- [x] sopra-fs24-group-37/sopra-fs24-server#79
