### ISSUE TITLE
As a registered user, I want to be able to log into the application and see who is currently logged in to see who I can initiate mutual games with.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#2]
- [x] Registered users should be able to log in and see all other registered users in the login area.
- [x] Registered users should be able to log out and log back in.
- [x] If the login is not successful, an error message is shown (e.g., ``Wrong username or password''), and the user is taken back to the login screen.

- [x] sopra-fs24-group-37/sopra-fs24-client#5
- [x] sopra-fs24-group-37/sopra-fs24-server#26
- [x] sopra-fs24-group-37/sopra-fs24-server#27
- [x] sopra-fs24-group-37/sopra-fs24-client#6
- [x] sopra-fs24-group-37/sopra-fs24-client#7
- [x] sopra-fs24-group-37/sopra-fs24-server#30
- [x] sopra-fs24-group-37/sopra-fs24-client#43
- [x] sopra-fs24-group-37/sopra-fs24-server#32
