### ISSUE TITLE
As a logged in user, I want to be able to see other users' statistics.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#3]
- [x] Logged in users are able to look at each others profiles.
- [x] Profiles should include statistics such as games played and games won.

- [x] sopra-fs24-group-37/sopra-fs24-client#8
- [x] sopra-fs24-group-37/sopra-fs24-client#9
- [x] sopra-fs24-group-37/sopra-fs24-server#35
- [x] sopra-fs24-group-37/sopra-fs24-client#44
