### ISSUE TITLE
As a logged in user, I want to be able to initiate a new game for other logged in users to join.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#4]
- [ ] Logged in users can create a new game by pressing on a button "Start game".
- [ ] Upon pressing the button, the player is directed to a page that says "Waiting for other players to join".
- [ ] Users who have joined the game are shown on the screen.
- [ ] Users logged in are shown a list of already existing games in the setup area. If no game has been initiated yet, the relevant area will be empty and the text "No game has been started so far" will be shown.

- [x] sopra-fs24-group-37/sopra-fs24-client#10
- [x] sopra-fs24-group-37/sopra-fs24-server#38
- [x] sopra-fs24-group-37/sopra-fs24-server#39
- [x] sopra-fs24-group-37/sopra-fs24-client#11
- [x] sopra-fs24-group-37/sopra-fs24-client#12
- [x] sopra-fs24-group-37/sopra-fs24-client#13
- [x] sopra-fs24-group-37/sopra-fs24-client#14
