### ISSUE TITLE
As a logged in user, I want to be able to join an existing game initiated by another logged in user.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#5]
- [ ] Logged in users are shown a list of already existing games in the setup area.
- [ ] If another logged in user has already initiated a game, other logged in users can select the relevant game by clicking on it on the setup area.
- [ ] If the chosen game requires a password, a window "Please enter password" with an input field will appear.
- [ ] A maximum of four players can join a game. If a game has already been joined by four users, the game is still shown in the login area but can no longer be selected.
- [ ] Once I have joined an existing game, I can chose to leave it if it hasn't started yet.

- [x] sopra-fs24-group-37/sopra-fs24-client#15
- [x] sopra-fs24-group-37/sopra-fs24-client#16
- [x] sopra-fs24-group-37/sopra-fs24-client#19
- [x] sopra-fs24-group-37/sopra-fs24-server#49
- [x] sopra-fs24-group-37/sopra-fs24-server#50
