### ISSUE TITLE
As a logged in user, I want to be able to start the game once the desired number of users have signed up for it.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#7]
- [ ] As soon as at least one other user has joined the game, a button "Start game" is shown.
- [ ] The user who initiated the game can start the game by pressing the "Start game" button.
- [ ] When pressing the "Start Game" button, the game starts with all users who have signed up for it.

- [x] sopra-fs24-group-37/sopra-fs24-client#22
- [x] sopra-fs24-group-37/sopra-fs24-client#23
- [x] sopra-fs24-group-37/sopra-fs24-server#55
