### ISSUE TITLE
As a game master, I want to be able to change the game parameters. 

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#8]
- [ ] The game master can change variable parameters such as guessing time.
- [ ] The other participants will be able to see the parameters but will not be able to edit them.
- [ ] By pressing the "Start game" button, the game starts with the set parameters.

- [x] sopra-fs24-group-37/sopra-fs24-client#24
- [x] sopra-fs24-group-37/sopra-fs24-client#25
- [x] sopra-fs24-group-37/sopra-fs24-server#58
- [x] sopra-fs24-group-37/sopra-fs24-server#141
