### ISSUE TITLE
As a game master, I want to be able to set a password for my created game.

### ISSUE THREAD

**Issue by gf237** [sopra-fs24-group-37/sopra-fs24-server#9]
- [ ] The game master can set a password to restrict, who can enter his game.
- [ ] Other players will only be able to join if the correct password has been entered.

- [x] sopra-fs24-group-37/sopra-fs24-client#26
- [x] sopra-fs24-group-37/sopra-fs24-server#60
- [x] sopra-fs24-group-37/sopra-fs24-client#17
